### ISSUE TITLE
RHS compatybility

### ISSUE THREAD

**Issue by Przemro** [deltagamer/DEGA_Static_Line#1]
Sorry if this is wrong place.
Could you add RHS C-130, so your mod can work with it?

**Comment by deltagamer** [comment]
Hey Przemro,

I'm not really planning on continuing this mod as I've expanded it off into parachutes in general. I suggest you take a look at the below link as this mod has similar features and should hopefully work with RHS vehicles.


https://github.com/deltagamer/DEGA_Parachutes
